### ISSUE TITLE
We need to write up documentation and make it available as system help

### ISSUE THREAD

**Issue by timlinux** [kartoza/stream_feature_extractor#22]
# Problem

We need to have good end-user and technical documentation so that users can understand how to use the system, and developers can understand how to extend it.
# Proposed solution

Write up documentation in sphinx explaining how to use the system and link it to a context help button at appropriate places in the UI.
# Expected outcome

The user should have clear instructions on how to use the system.

**Comment by timlinux** [comment]
Here are some graphics to go with documentation. Note that watershed delineation is still unresolved.

![stream-feature-extraction1](https://cloud.githubusercontent.com/assets/178003/2645273/fe9c7894-bf30-11e3-837d-4bed64138779.png)

![stream-feature-extraction2](https://cloud.githubusercontent.com/assets/178003/2645284/02f9fbb4-bf31-11e3-9123-ca5c056a5d22.png)

![stream-feature-extraction3](https://cloud.githubusercontent.com/assets/178003/2645286/08e7f044-bf31-11e3-85df-b2fc4974f46b.png)

@ismailsunni FYI

**Comment by ismailsunni** [comment]
Some questions:
1. Based on the image, there is possibility that `branch` == `confluence`. For example, if `upstream node` = `downstream node` = 5. Is it ok?
2. How we define two nodes are same?
3. What's the different between `watershed` and `well` ? By looking at the image only, `watershed` has more than one `downstream node`. But, we define that `well` can have more than one `downstream node`.

**Comment by timlinux** [comment]
> Some questions:
> 1. Based on the image, there is possibility that branch == confluence. For example, if upstream node = downstream node = 5. Is it ok?

No the logic is based on node counts, not on node id's

> 1. How we define two nodes are same?

They are the same by having the same geographic position within a user defined tolerance.

> 1. What's the different between watershed and well ? By looking at the image only, watershed has more than one downstream node. But, we define that well can have more than one downstream node.

I still have to figure out a decent rule for a watershed - could you do a little research on this?

**Comment by ismailsunni** [comment]
> No the logic is based on node counts, not on node id's

Sorry, it should be count(upstream node) = count(downstream node) = 5

> I still have to figure out a decent rule for a watershed - could you do a little research on this?

Ok

**Comment by timlinux** [comment]
> Sorry, it should be count(upstream node) = count(downstream node) = 5

Ok in this case if a single node has > 1 upstream nodes and > 1 downstream nodes, it is both a branch and a confluence, which is no problem.

**Comment by timlinux** [comment]
Adding this table from #12 as it will be useful to add something like this in the docs:

| id | line_id | node_type | node_list | node_count | well | sink | confluence | branch | has_pseudonodes | watershed |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 1 | 1 | upstream | 5, 10 , 15 | 4 | 1 | 0 | 0 | 0 | 0 | 0 |
| 2 | 1 | downstream | 12, 14,  44 | 4 | 0 | 0 | 0 | 0 | 0 | 0 |

**Comment by ismailsunni** [comment]
By the way:
Watershed : An area or ridge of land that separates waters flowing to different rivers, basins, or seas.

I think, watershed refers to the final part of the stream river (and go to the sea)

**Comment by timlinux** [comment]
Yeah sorry I already know what it is, I meant for you to do some research for an algorithm that delineates a watershed (as opposed to a well). I think that there isn't an easy way to discern between well and watershed.

> I think, watershed refers to the final part of the stream river (and go to the sea)

That is normally referred to as a water catchment area.

@tilladams Do you have some feedback on this - what is the client expecting for watershed determination? i.e. how should we discern between wells (no upstream nodes) and watersheds (no upstream nodes).

**Comment by ismailsunni** [comment]
Update the rules based on @timlinux 's email
1. **Crossing** / _Kreuzung_ (two features cross each other)
   ![crossing](https://cloud.githubusercontent.com/assets/1421861/2994040/7b76f266-dcc5-11e3-8650-124a5c3dba7c.png)
2. **Pseudonode**  / _Pseudonode_ (1 upstream and one downstream) the node is superflous as it can be represented by one line instead of two
   ![pesudonode](https://cloud.githubusercontent.com/assets/1421861/2994046/9e51d74c-dcc5-11e3-8884-d271b5c4c10a.png)
3. **Well** / _Quelle_ (1 upstream node, no downstream nodes)
   ![well](https://cloud.githubusercontent.com/assets/1421861/2994057/dea20c40-dcc5-11e3-9a3d-fa64776985b4.png)
4. **Sink**  / _Senke_ (no upstream, 1 downstream)
   ![sink](https://cloud.githubusercontent.com/assets/1421861/2994060/e874db9e-dcc5-11e3-9ece-fbe0402f7736.png)
5. **Watershed**  / _Top_ (> 1 upstream, no downstream)
   ![top](https://cloud.githubusercontent.com/assets/1421861/2994063/efb51bda-dcc5-11e3-9dee-7db1763547be.png)
6. **Unseparated**  / _Ungetrennter_ (only 1 upstream or only 1 downstream and intersects with one or more other lines ). Note that in the lines below, there is only one node under the star, the other line has no node at the position of the star.
   ![unseparated](https://cloud.githubusercontent.com/assets/1421861/2994067/fb8b10a4-dcc5-11e3-8f78-a14c45460787.png)
7. **Unclear bifurcation**  / _Unklare Bifukation_ (>1 upstream, > 1 downstream)
   ![unclear bifurcation](https://cloud.githubusercontent.com/assets/1421861/2994070/091f8466-dcc6-11e3-800a-26a41f24e0de.png)
8. **Tributary**  / _Verzweigung_  (branch) (1 downstream, 2 or more upstream)
   ![tributary](https://cloud.githubusercontent.com/assets/1421861/2994079/1f4a0a0e-dcc6-11e3-99ca-938d12d0101d.png)
9. **Confluence** / _Zusammenfluss_ (1 upstream and 2 or more downstream)
   ![confluence](https://cloud.githubusercontent.com/assets/1421861/2994081/272bb074-dcc6-11e3-919b-c88557aef1ef.png)

**Comment by ismailsunni** [comment]
Another notes:

> There is one other thing to consider - I believe a confluence can be valid in in streams > outstreams and a tributary can be valid if outstreams > instreams. So for example a node with 3 upstream and 2 downstream would be considered a confluence. And a node with 2 upstream and 3 downstream would be considered a tributary.

So, I can conclude that:
1. Unclear bifurcation has the same number of upstream nodes and downstream nodes and both of them are more than one. So 1 < number of upstream nodes = number downstream nodes
2. Branch 1 <= number of upstream nodes < number downstream nodes
2. Confluence 1 <= number of downstream nodes < number upstream nodes

Am I right?

**Comment by timlinux** [comment]
Hi

Sent from my mobile phone
On 16 May 2014 9:10 AM, "Ismail Sunni" notifications@github.com wrote:

> Another notes:
> 
> > There is one other thing to consider - I believe a confluence can be
> > valid in in streams > outstreams and a tributary can be valid if outstreams
> > instreams. So for example a node with 3 upstream and 2 downstream would
> > be considered a confluence. And a node with 2 upstream and 3 downstream
> > would be considered a tributary.
> 
> So, I can conclude that:
> 1. Unclear bifurcation has the same number of upstream nodes and
> downstream nodes and both of them are more than one. So 1 < number of
> upstream nodes = number downstream nodes
> 2. Branch 1 <= number of upstream nodes < number downstream nodes
> 2. Confluence 1 <= number of downstream nodes < number upstream nodes
> 
> Am I right?

Yes with addition that branch has at least 1 upstream and 2 downstream.
Confluence has at least 2 upstream and 1 downstream.

Thanks

Tim
